Class opc.ua.bp.GIP03ProcessOEEShiftWorkOrder.GIP03ProcessOEEShiftWorkOrderResp Extends Ens.Response
{

/// Data output
Property Data As opc.ua.data.GIP03.serving.GIP03OEESHIFTWORKORDER;

Storage Default
{
<Data name="GIP03ProcessOEEShiftWorkOrderRespDefaultData">
<Subscript>"GIP03ProcessOEEShiftWorkOrderResp"</Subscript>
<Value name="1">
<Value>Data</Value>
</Value>
</Data>
<DefaultData>GIP03ProcessOEEShiftWorkOrderRespDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
