Class opc.ua.bp.GIP03ProcessOEEShiftTimeSlide.GIP03ProcessOEEShiftTimeSlideResp Extends Ens.Response
{

/// Data output
Property Data As opc.ua.data.GIP03.serving.GIP03OEESHIFTTIMESLIDE;

Storage Default
{
<Data name="GIP03ProcessOEEShiftTimeSlideRespDefaultData">
<Subscript>"GIP03ProcessOEEShiftTimeSlideResp"</Subscript>
<Value name="1">
<Value>Data</Value>
</Value>
</Data>
<DefaultData>GIP03ProcessOEEShiftTimeSlideRespDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
